#1 ultimo registro
SELECT * FROM Nom_nomina_definitiva ORDER BY REGISTRO DESC LIMIT 1

#1 Fecha de creación ultimo registro
SELECT FCHE_CRE FROM Nom_nomina_definitiva ORDER BY REGISTRO DESC LIMIT 1

#2 Creacion de las tablas

CREATE TABLE `REG_SOLICITUDES_INGRESOS` ( `id_SOLICITUD` INT NOT NULL , `DOCUMENTO` INT NOT NULL , `APELLIDOS` VARCHAR(30) NOT NULL , `NOMBRES` VARCHAR(30) NOT NULL ) ENGINE = InnoDB;
CREATE TABLE `NOM_CONCEPTOS_NOMINA` ( `ID_CONCEPTO` INT NOT NULL , `DESC_CONCEPTO` VARCHAR(30) NOT NULL , `COD_CONCEPTO` INT NOT NULL ) ENGINE = InnoDB;
CREATE TABLE `NOM_CONCEPTOS_NOMINA` ( `ID_CONCEPTO` INT NOT NULL , `DESC_CONCEPTO` VARCHAR(30) NOT NULL , `COD_CONCEPTO` INT NOT NULL ) ENGINE = InnoDB;
CREATE TABLE `nom_nomina_definitiva` ( `REGISTRO` INT NOT NULL , `FCH_CRE` TIMESTAMP NOT NULL , `ID_CONCEPTO` INT NOT NULL , `ID_EMPLEADO` INT NOT NULL , `VAL_NOMINA` INT NOT NULL , `CANTIDAD` INT NOT NULL ) ENGINE = InnoDB;

#2 OBTENER REGISTROS ESPECIFICOS DE REGISTRO='8935462'
SELECT NCN.cod_concepto, NCN.DESC_CONCEPTO, NE.ID_EMPLEADO, RGI.NUM_DOC_IDENTIDAD, RGI.APELLIDOS, RGI.NOMBRES NND.VAL_NOMINA, NND.CANTIDAD
FROM NOM_CONCEPTOS_NOMINA NCN, NOM_EMPLEADOS NE, REG_SOLICITUDES_INGRESO RGI, NOM_NOMINA_DEFINITIVA NND
WHERE NND.REGISTRO='8935462' AND NND.ID_CONCEPTO=NCN.ID_CONCEPTO, AND NE.ID_EMPLEADO=NND.ID_EMPLEADO AND NE.ID_SOLICITUD=RGI.ID_SOLICITUD

#Crear tabla con especificaciones SQL
CREATE TABLE log_consulta_nom_nomina_definitiva (
    id_registro INT NOT NULL,
    Usuario VARCHAR(30),
    fecha datetime,
    operación VARCHAR(10),
    descripción_de_evento VARCHAR(120),
    PRIMARY KEY (id_registro)
);

#3 STORE PROCEDURE - PHPMyAdmin
#Recibe los 4 parametros solicitados y evalua mediante ifs cual es el procedimiento que debe realizar según el parametro Evento

DELIMITER //
CREATE PROCEDURE D (IN DOC_IDENTIDAD VARCHAR(50),IN Evento INT,IN USUARIO VARCHAR(50),IN REGISTRO_NOM_NOMINA_DEFINITIVA INT)

BEGIN

    #consultar
    IF(Evento=1) THEN
        SELECT * FROM `nom_nomina_definitiva`WHERE `REGISTRO` = DOC_IDENTIDAD AND `nom_nomina_definitiva`>'01/01/2014';
	END IF;
    
    #insertar
    IF(Evento=2) THEN
        INSERT INTO `nom_nomina_definitiva` (`REGISTRO`, `FCH_CRE`, `ID_CONCEPTO`, `ID_EMPLEADO`, `VAL_NOMINA`, `CANTIDAD`) VALUES (DOC_IDENTIDAD, current_timestamp(),USUARIO, USUARIO, DOC_IDENTIDAD, REGISTRO_NOM_NOMINA_DEFINITIVA);
	END IF;
    
    #Eliminar
    IF(Evento=3) THEN
        DELETE FROM `nom_nomina_definitiva` WHERE REGISTRO=DOC_IDENTIDAD
	END IF;
    
END //
DELIMITER ;

#Llamarlo con CALL USP_CONSULTA_NOMINA _POR_DOCUMENTO (4 parametros)

Evento 1 Seleccionar
Evento 2 Insertar
Evento 3 Eliminar